### ISSUE TITLE
Oh, the places you've been -- summary

### ISSUE THREAD

**Issue by mirandawei** [sebastianmeiser/CCS-talks#1]
Hi Sebastian,

Thank you so much for coming to my talk! 

I just wanted to clarify one thing that you wrote in your summary: in the first bullet point, "... then compared this text with what the user typed" this should be something like "... then compared this text with the (cleaned) text of the current web page that the user was on." We didn't collect any text that the user inputted themselves onto the web page, just the content of the page itself!

Thanks again for coming and writing an excellent summary, not sure if I could've done a better job!

**Comment by sebastianmeiser** [comment]
Thanks, I've changed it and will push the changes soon. :)
